### ISSUE TITLE
[Feature] Footer Section

### ISSUE THREAD

**Issue by parthpathakpp1** [Counselllor/Counsellor-Web#10]
This site should I have a Footer section .

**Why Footer Section should be there ? -:**
1. Navigation and Site Map: The footer provides easy navigation and a site map, helping users find information quickly.

2. Contact Information: Display important contact details like phone numbers, email addresses, and social media links.

3. Additional Links and Resources: Showcase related links, partners, and important pages that don't fit in the main navigation.

4. Copyright and Legal Information: Include copyright notices, disclaimers, and terms of service to protect intellectual property and ensure compliance.

**Requirements - :**
1.Your Social media links . 

**I will make a good Footer section for your website .**

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23.

**Comment by thestarsahil** [comment]
@parthpathakpp1 
Regarding your offer to create a Footer section for our website, I appreciate your willingness to contribute. We would be glad to have your assistance in designing and implementing a visually appealing and functional Footer section. Please proceed with creating the Footer design, including our social media links. Once you have it ready, kindly share it with us so that we can review and integrate it into the website. Thank you for your valuable contribution!

**Comment by vk20july** [comment]
@thestarsahil sir i want to work on this issue under gssoc'23
