### ISSUE TITLE
BUG: No Need of Navbar Outside Login Pages Instead Add new one

### ISSUE THREAD

**Issue by MastanSayyad** [Counselllor/Counsellor-Web#1031]
Hey @thestarsahil 

I think there is no need of this navbar outside login pages as these navlinks redirects us to the main pages inside login 
only after login the pages should have the this navbar

![image](https://github.com/user-attachments/assets/58f3b902-146c-42c2-b855-43ec189e3444)

It is causing various bugs and issue:

https://github.com/user-attachments/assets/afeb024f-412c-455b-a0d6-016c08715a77

and for outside pages, we can add a different navbar whose links are:
- Home
- About Us
- Contact Us
- Our Contributors 
- Login

Like this:

![image](https://github.com/user-attachments/assets/0cfe25fb-5581-46ab-af37-087a8dab4207)

It will ensure the user experience throughout the website, more engaging and less confusing!!

**Comment by MastanSayyad** [comment]
@thestarsahil Please assign this issue to me!

**Comment by thestarsahil** [comment]
As the main purpose to keep this navbar , when user not logged in 
It will try some features and understand some thing for that why we implemented navbar everwhere 
Before login navbar 
After login navbar , it will changed 

But ya that's a bug if you can fix this , if user not logged in it will not redirect to dashboard page , 
It will redirect to only login page 
After logged in , if user logged in the redirect to dashboard page if user shifted to error page so that user can back to dashboard page

**Comment by MastanSayyad** [comment]
> As the main purpose to keep this navbar , when user not logged in 
> It will try some features and understand some thing for that why we implemented navbar everwhere 
> Before login navbar 
> After login navbar , it will changed 
> 
> But ya that's a bug if you can fix this , if user not logged in it will not redirect to dashboard page , 
> It will redirect to only login page 
> After logged in , if user logged in the redirect to dashboard page if user shifted to error page so that user can back to dashboard page 

Okay, i understand, @thestarsahil
