### ISSUE TITLE
Login and Sign Up UI

### ISSUE THREAD

**Issue by radzhiv25** [Counselllor/Counsellor-Web#13]
I would like to revamp the over all Look of both the sign up and login UI

Please consider this under GSSOC'23

**Comment by thestarsahil** [comment]
@radzhiv25 
Thank you for your interest in revamping the Sign Up and Login UI for our project. We appreciate your enthusiasm and would be glad to consider your contribution under GSSOC'23.

To proceed with this task, we kindly request you to create a mockup or design proposal for the new UI. Focus on elements such as color schemes, typography, layout, and any additional features or enhancements you think would improve the user experience. Once you have the design ready, please share it with us so that we can review and discuss its implementation.

We are excited to see your ideas and look forward to collaborating with you to create a revamped and impressive UI for the Sign Up and Login pages. Thank you for your valuable contribution to GSSOC'23!

**Comment by radzhiv25** [comment]
> @radzhiv25 Thank you for your interest in revamping the Sign Up and Login UI for our project. We appreciate your enthusiasm and would be glad to consider your contribution under GSSOC'23.
> 
> To proceed with this task, we kindly request you to create a mockup or design proposal for the new UI. Focus on elements such as color schemes, typography, layout, and any additional features or enhancements you think would improve the user experience. Once you have the design ready, please share it with us so that we can review and discuss its implementation.
> 
> We are excited to see your ideas and look forward to collaborating with you to create a revamped and impressive UI for the Sign Up and Login pages. Thank you for your valuable contribution to GSSOC'23!

Sure will do that

**Comment by radzhiv25** [comment]
> > @radzhiv25 Thank you for your interest in revamping the Sign Up and Login UI for our project. We appreciate your enthusiasm and would be glad to consider your contribution under GSSOC'23.
> > To proceed with this task, we kindly request you to create a mockup or design proposal for the new UI. Focus on elements such as color schemes, typography, layout, and any additional features or enhancements you think would improve the user experience. Once you have the design ready, please share it with us so that we can review and discuss its implementation.
> > We are excited to see your ideas and look forward to collaborating with you to create a revamped and impressive UI for the Sign Up and Login pages. Thank you for your valuable contribution to GSSOC'23!
> 
> Sure will do that

<img width="432" alt="image" src="https://github.com/thestarsahil/Counsellor/assets/84130482/733ea896-606f-4670-900b-af60256f4960">
Relevant to this will be sign up page 
<img width="310" alt="image" src="https://github.com/thestarsahil/Counsellor/assets/84130482/37068aab-c9c0-47ec-99b7-afc27fd2e52d">
If you want more changes could be made

**Comment by Gun2902** [comment]
can u assign me this isssue
