### ISSUE TITLE
Login Page UI alignment issue

### ISSUE THREAD

**Issue by aashi-ihsaa** [Counselllor/Counsellor-Web#31]
![Counsellor_Login](https://github.com/thestarsahil/Counsellor/assets/96407263/020b2ae4-a82c-42d7-b7d2-44342118636a)
In Login page UI, the "For the students by the students" image and text are not centrally aligned properly. They are making ui look unclean. Assign me this issue under GSSOC'23 to make sure about proper alignment.

**Comment by thestarsahil** [comment]
This comment is to assign the issue of "For the students by the students" image and text not being centrally aligned properly to @aashi-ihsaa 
The issue is making the UI look unclean, and it needs to be fixed.
Please ensure that the image and text are centrally aligned properly, and that the UI looks clean and professional.
Thank you for your time and attention to this issue.
