### ISSUE TITLE
[Feature] Contact Us Section

### ISSUE THREAD

**Issue by parthpathakpp1** [Counselllor/Counsellor-Web#9]
There should be a contact us section . Which will help visitors to contact you and send their messages . I will make contact us section for you .

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23 .

**Comment by kasturimandlik** [comment]
Hello ,
I would like to design the frontend of contact us page which will help the user to contact or share their experience with the owner of the website easily. This will help to enhance the user experience.
The page will have a form which collects necessary details like email address, mobile number, message, etc.
Please assign me this issue.
I would like to work on this issue under GSSOC'23.

**Comment by kasturimandlik** [comment]
@thestarsahil Please assign me this issue

**Comment by Yogesh-7523** [comment]
@thestarsahil i would like to contribute to this amazing open-source project in solving the issue of  Contact Us Section we can add various mandatory details that would be required to make the project more responsive, 
can you assign this to me under GSSOC 23 I am fresher in open source and want to gain experience

**Comment by thestarsahil** [comment]
Hello @parthpathakpp1 @Yogesh-7523 @kasturimandlik 

Thank you for expressing your interest in designing the frontend of the Contact Us page. It's great to hear that you want to improve the user experience by allowing users to easily contact and share their experiences with the website owner.

I appreciate your enthusiasm and would be happy to assign you this issue under GSSOC'23. Before that, I would like to discuss and review the design of the Contact Us page. Please provide me with the UI design or mockup of the page so that I can assess its suitability and alignment with the project's requirements.

Once I have reviewed the design and find it suitable, I will assign you the issue to proceed with the frontend development of the Contact Us page.

Thank you for your contribution, and I look forward to reviewing your design.

**Comment by parthpathakpp1** [comment]
> 

@thestarsahil 
can three of us collaborate and make it happen??

**Comment by thestarsahil** [comment]
Yes, absolutely! Collaboration is key to achieving the desired improvements 
Feel free to initiate discussions, ask questions, and engage with other contributors to foster a collaborative environment. Together, you can make significant progress and achieve the desired improvements.

Best of luck with your collaboration efforts, and thank you for your dedication to the project!

**Comment by parthpathakpp1** [comment]
> Yes, absolutely! Collaboration is key to achieving the desired improvements Feel free to initiate discussions, ask questions, and engage with other contributors to foster a collaborative environment. Together, you can make significant progress and achieve the desired improvements.
> 
> Best of luck with your collaboration efforts, and thank you for your dedication to the project!

OK

**Comment by parthpathakpp1** [comment]
@kasturimandlik @Yogesh-7523 Guys up for the collaboration ? If yes send your discord id's.

**Comment by kasturimandlik** [comment]
@parthpathakpp1 I am up for this collaboration.

**Comment by parthpathakpp1** [comment]
> @parthpathakpp1 I am up for this collaboration.

can you share your discord id .

**Comment by Yogesh-7523** [comment]
hey great idea of collaboration 
discord id Nemesis#9851
@parthpathakpp1

**Comment by kasturimandlik** [comment]
@parthpathakpp1 
Discord id: kasturimandlik#7190

**Comment by thestarsahil** [comment]
Are you working on ?
Should i close this

**Comment by Yogesh-7523** [comment]
Close it sir
